apiVersion: v1
kind: Service
metadata:
  name: postgredb-svc
  namespace: shops
spec:
  type: ClusterIP
  selector:
    db: postgredb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432