apiVersion: v1
kind: Service
metadata:
  name: fakeshop-svc
  namespace: shops
spec:
  type: LoadBalancer
  selector:
    app: fakeshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000